# Generated by Django 5.1.1 on 2024-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_alter_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
